name: Publish resume in JSONResume format as Github Page

# Controls when the action will run.
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_run:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"

  build:
    runs-on: ubuntu-latest
    needs: check_run
    steps:
      - uses: actions/checkout@v2
      - name: YAML/JSON/XML Converter Action
        uses: fabasoad/yaml-json-xml-converter-action@v1.0.14
        id: yaml2json
        with:
          path: 'resume.yaml'
          from: 'yaml'
          to: 'json'
      - name: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: resume.json
          json: ${{ steps.yaml2json.outputs.data }}
      - uses: constructorfleet/action-jsonresume-export@v1.0
        name: Export resume as HTML
        with:
          theme: eloquent-mod
          resume_filepath: resume.json
          # modifies the index.html in-place
          output_filepath: docs/index.html
      - uses: constructorfleet/action-jsonresume-export@v1.0
          name: Export resume as PDF
          with:
            theme: eloquent-mod
            resume_filepath: resume.json
            # modifies the index.html in-place
            output_filepath: docs/resume.teagan.glenn.pdf
      - name: Commit published HTML
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if [ -n "$(git status --porcelain docs/index.html)" ]; then
            git add docs/index.html
            git add docs/resume.teagan.glenn.pdf
            git commit -m "[ci skip] chore(docs/index.html): update resume page"
            echo ::set-output name=exit_code::0
          else
            echo ::set-output name=exit_code::1
          fi
      - name: Push changes
        uses: ad-m/github-push-action@master
        if: steps.commit.outputs.exit_code == 0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          force: true
          branch: published
